### ISSUE TITLE
Footer and Creator adjustments needed

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/omeka-theme-seasons#11]
From Cristela:

**Note**: Contact Us should link to dlp AT ucsd DOT edu

--
Okay, there’s display issues Firefox (see below), and for the footer, we would like it to contain:  
 
Presented by the UC San Diego Library
UC San Diego 9500 Gilman Dr. La Jolla, CA 92093 (858) 534-2230
Copyright ©2010 Regents of the University of California. All rights reserved.
Contact Us 
 
The logo is rather large in Firefox and not responsive.  Any chance we can at least resize it?
 
![image](https://cloud.githubusercontent.com/assets/67506/25732183/c52050b8-3101-11e7-8459-d5134b99d431.png)
 
 
For Creator, depending on the spacing it sometimes overlaps with the thumbnail.  Is it possible to work on the alignment and remove the bullet?  (The bullet does not show up in Chrome)
 
![image](https://cloud.githubusercontent.com/assets/67506/25732175/b7af8bf6-3101-11e7-8f22-6f1081752210.png)

**Comment by dt-ucsd** [comment]
Added content to the theme's footer via the built-in appearance/theme interface.

**Comment by dt-ucsd** [comment]
Followed up on logo sizing issue in footer with Cristela, turned out to be a non-issue. Both she and Tamara verified that it is rendering correctly in their browsers.

**Comment by dt-ucsd** [comment]
@mcritchlow The "alignment" error referred to in this issue is not a bug, it is by design. Note the screenshot below. Default "Tags" content flows in the same way if the description is short enough.

<img width="727" alt="" src="https://cloud.githubusercontent.com/assets/2448340/26011100/886657b8-3704-11e7-80e6-eef42ff6fc67.png">

It is "correctable" by redesigning the way content flows within that container, but note that that will affect the flow of long descriptions as well (I.e., they will no longer flow beneath the thumbnail). Additionally, care will need to be taken to ensure that the mobile-first design of the theme is respected.

How shall we proceed?

**Comment by dt-ucsd** [comment]
As for the bullet being visible, I am following up with Cristela and Tamara. I don't see it on any of my browsers, and if my hunch is correct, then like the logo, this may turn out to be a non-issue.

**Comment by mcritchlow** [comment]
Thanks for all the updates. 

As for the content flow/wrapping issue, I'm not sure exactly how to proceed on that. @gamontoya, thoughts?

**Comment by gamontoya** [comment]
@mcritchlow @dt-ucsd @cgarciaspitz Matt/David: regarding the flow/wrapping issue, I think that Cristela needs to make the call on this, although a flow of long descriptions no longer working should be an issue.

**Comment by gamontoya** [comment]
@dt-ucsd @cgarciaspitz By the way, I do not see the bullets in my FF or IE.

@cgarciaspitz This is just me, but I don't like the font this website uses.

**Comment by gamontoya** [comment]
@cgarciaspitz This is waiting on you.
