### ISSUE TITLE
Make "Featured Item" thumbnail smaller

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#2]
**Issue:**

- At the current size, the image quality is poor.
- Can the size be constrained so it doesn't get too big and lead to grainy images? Responsive design issue?

See:
https://library.ucsd.edu/tellushowucit/

Example:
![image2017-2-2 18-27-15](https://cloud.githubusercontent.com/assets/4314914/24419952/efca5a8a-13a5-11e7-9cce-1f1080240e6f.png)

**Comment by dt-ucsd** [comment]
- The size can be constrained. Need to verify upper limit of thumbnail resolution first though. Otherwise the problem won't be solved.

- Not a responsive design issue, more of just a general design issue. Folks who designed the featured item card may not have taken thumbnail resolution into account. Might not have even been an issue for them, could have just  been a choice the made with knowledge of the resolution trade-off for upper desktop resolutions.

It is solvable, but these are just my initial thoughts. Work is ongoing.

**Comment by dt-ucsd** [comment]
Thumbnails are 200px by 200px. Size can be constrained via CSS.

**Comment by dt-ucsd** [comment]
Probably the best way to approach this issue would be to resize the column containing the featured item in the theme.

Maybe also adjust the size of the parent container for the desktop view. It shouldn't be as wide as it is.

**Comment by dt-ucsd** [comment]
Featured image with width capped at 200px and centered:

![image](https://cloud.githubusercontent.com/assets/2448340/25410131/e6d35e2e-29c9-11e7-8930-e53b3456f1e4.png)
