### ISSUE TITLE
Update footer to include Library logo, etc.

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/omeka-theme-seasons#3]
**Issue:**

- The footer should have the Library's contact info, logo, and link back to the Library home page.
- Change from this:

![image2017-2-2 18-27-15](https://cloud.githubusercontent.com/assets/4314914/24420179/d1c5ae6c-13a6-11e7-9660-1b082db76c23.png)
- To something more like this:

![image2017-2-2 18-29-27](https://cloud.githubusercontent.com/assets/4314914/24420189/dac9ea50-13a6-11e7-8492-196e7602325b.png)

- See:
    - https://library.ucsd.edu/tellushowucit/

**Comment by mcritchlow** [comment]
Noting that in the coming Sprint 08, David will do a preliminary pass at getting a UCSD footer in place with the logo. A larger design discussion will undoubtedly need to happen, but this should get closer to the site actually looking more like a UCSD site.

**Comment by dt-ucsd** [comment]
I updated the footer to include the logo. Logo links to the Library PWS.

Note that the left-hand content is included via custom HTML control in theme's settings. So that can be whatever address/info you need it to be. Having it remain custom HTML has the benefit of allowings Omeka admins to update that data without needing a theme update.

![image](https://cloud.githubusercontent.com/assets/2448340/25408038/7746d89a-29c1-11e7-82da-da0565c5cb78.png)

**Comment by dt-ucsd** [comment]
HTML I used for custom footer text:

`<p>UC San Diego 9500 Gilman Dr. La Jolla, CA 92093 (858) 534-2230<br /> Copyright ©2017 Regents of the University of California. All rights reserved.<br /><a href="https://library.ucsd.edu">UC San Diego Library Website</a></p>`
